### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "ado",
    "password": "123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "ado",
    "password": "123"
}


### -- Tasks Requests 

### create task
POST http://localhost:3000/api/tasks/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTQ1NzkzLCJleHAiOjE3NTQ1NDkzOTN9.cOMWGuX2zeYJ6hdWubbZHMp1B7153IKONfk6p_-Y4ww

{
    "title": "Task 2",
    "description": "This is task 2"
}

### update task

PUT http://localhost:3000/api/tasks/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0NTUwMDM4LCJleHAiOjE3NTQ1NTM2Mzh9.YE8XZz0Z74CrAtGXwppCC4kCB9k4veC5Engq8OMKH_A

{
    "title": "Task 1 updated 2",
    "description": "This is task 1 updated 222",
    "status": "true"
}

### Delete task by id
DELETE http://localhost:3000/api/tasks/delete/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTQ1NzkzLCJleHAiOjE3NTQ1NDkzOTN9.cOMWGuX2zeYJ6hdWubbZHMp1B7153IKONfk6p_-Y4ww

### Get User tasks
GET http://localhost:3000/api/tasks/get-tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTQ1NzkzLCJleHAiOjE3NTQ1NDkzOTN9.cOMWGuX2zeYJ6hdWubbZHMp1B7153IKONfk6p_-Y4ww
